function(talal_find_config package_name)
    find_package(${package_name} CONFIG QUIET)
    set(found_var "${package_name}_FOUND")
    set(found_value FALSE)
    if(DEFINED ${found_var})
        set(found_value "${${found_var}}")
    endif()
    if(found_value)
        set_property(GLOBAL APPEND PROPERTY TALAL_FOUND_DEPENDENCIES "${package_name}")
    else()
        set_property(GLOBAL APPEND PROPERTY TALAL_MISSING_DEPENDENCIES "${package_name}")
    endif()
endfunction()

function(talal_discover_manifest_dependencies target_name)
    find_package(fmt CONFIG QUIET)
    if(TARGET fmt::fmt)
        target_link_libraries(${target_name} INTERFACE fmt::fmt)
        set_property(GLOBAL APPEND PROPERTY TALAL_FOUND_DEPENDENCIES "fmt")
    else()
        set_property(GLOBAL APPEND PROPERTY TALAL_MISSING_DEPENDENCIES "fmt")
    endif()

    find_package(spdlog CONFIG QUIET)
    if(TARGET spdlog::spdlog)
        target_link_libraries(${target_name} INTERFACE spdlog::spdlog)
        set_property(GLOBAL APPEND PROPERTY TALAL_FOUND_DEPENDENCIES "spdlog")
    else()
        set_property(GLOBAL APPEND PROPERTY TALAL_MISSING_DEPENDENCIES "spdlog")
    endif()

    find_package(nlohmann_json CONFIG QUIET)
    if(TARGET nlohmann_json::nlohmann_json)
        target_link_libraries(${target_name} INTERFACE nlohmann_json::nlohmann_json)
        set_property(GLOBAL APPEND PROPERTY TALAL_FOUND_DEPENDENCIES "nlohmann-json")
    else()
        set_property(GLOBAL APPEND PROPERTY TALAL_MISSING_DEPENDENCIES "nlohmann-json")
    endif()

    find_package(glm CONFIG QUIET)
    if(TARGET glm::glm)
        target_link_libraries(${target_name} INTERFACE glm::glm)
        set_property(GLOBAL APPEND PROPERTY TALAL_FOUND_DEPENDENCIES "glm")
    else()
        set_property(GLOBAL APPEND PROPERTY TALAL_MISSING_DEPENDENCIES "glm")
    endif()

    if(TALAL_ENABLE_GRAPHICS)
        find_package(Vulkan QUIET)
        if(TARGET Vulkan::Vulkan)
            target_link_libraries(${target_name} INTERFACE Vulkan::Vulkan)
            set_property(GLOBAL APPEND PROPERTY TALAL_FOUND_DEPENDENCIES "vulkan")
        else()
            set_property(GLOBAL APPEND PROPERTY TALAL_MISSING_DEPENDENCIES "vulkan")
        endif()
        talal_find_config(directx-headers)
        talal_find_config(directxmath)
        talal_find_config(directx-dxc)
        talal_find_config(glslang)
        talal_find_config(spirv-tools)
        talal_find_config(spirv-cross)
        talal_find_config(vulkan-memory-allocator)
    endif()

    if(TALAL_ENABLE_AUDIO)
        talal_find_config(Opus)
        talal_find_config(lz4)
    endif()

    if(TALAL_ENABLE_NETWORK)
        talal_find_config(msquic)
    endif()

    if(TALAL_ENABLE_PHYSICS)
        talal_find_config(PhysX)
        talal_find_config(recastnavigation)
    endif()

    if(TALAL_ENABLE_TOOLS)
        talal_find_config(imgui)
        talal_find_config(Tracy)
        talal_find_config(fastgltf)
        talal_find_config(meshoptimizer)
        talal_find_config(tinyobjloader)
        talal_find_config(xxHash)
        talal_find_config(zstd)
    endif()

    if(TALAL_ENABLE_TESTS)
        talal_find_config(Catch2)
    endif()

    get_property(missing GLOBAL PROPERTY TALAL_MISSING_DEPENDENCIES)
    if(missing)
        list(REMOVE_DUPLICATES missing)
        message(STATUS "Dependencies not visible to CMake yet: ${missing}")
        if(TALAL_REQUIRE_DEPENDENCIES)
            message(FATAL_ERROR "Required dependencies are missing from the active vcpkg toolchain: ${missing}")
        endif()
    endif()
endfunction()
