function(talal_reject_in_source_build)
    if(CMAKE_SOURCE_DIR STREQUAL CMAKE_BINARY_DIR)
        message(FATAL_ERROR "In-source builds are disabled. Use scripts/setup_DEMO_WORKSTATION.ps1 or configure into out/build/<preset>.")
    endif()
endfunction()

function(talal_configure_output_directories)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib" PARENT_SCOPE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin" PARENT_SCOPE)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin" PARENT_SCOPE)
endfunction()

function(talal_print_phase0_summary)
    message(STATUS "TalalOpenWorldEngine phase: 0 repository/build foundation")
    message(STATUS "Target machine: ${TALAL_TARGET_MACHINE}")
    message(STATUS "CPU baseline: ${TALAL_CPU_BASELINE}")
    message(STATUS "Compile jobs: ${TALAL_LOCAL_COMPILE_JOBS}")
    message(STATUS "Shader jobs: ${TALAL_LOCAL_SHADER_JOBS}")
    message(STATUS "Asset jobs: ${TALAL_LOCAL_ASSET_JOBS}")
    message(STATUS "Vendor SDK root: ${TALAL_VENDOR_SDK_ROOT}")
endfunction()
